baseURL = "/"
author = "Steve Francia"
copyright = "Copyright © 2008–2021, Steve Francia, The lee.so, and Pim Snel; all rights reserved."
paginate = 3.0
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
ignoreErrors = [
  "error-remote-getjson"
]
theme = "Paper"
title = "Paper"

[params]
twitter = "nanxiaobei"
github = "nanxiaobei"
instagram = "nan.xiaobei"

[markup]

  [markup.goldmark]

    [markup.goldmark.renderer]
    unsafe = true

[menu]

  [[menu.main]]
  identifier = "about"
  name = "About"
  url = "/about/"
  weight = 10.0

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[privacy]

  [privacy.vimeo]
  disabled = false
  simple = true

  [privacy.twitter]
  disabled = false
  enableDNT = true
  simple = true

  [privacy.instagram]
  disabled = false
  simple = true

  [privacy.youtube]
  disabled = false
  privacyEnhanced = true

[services]

  [services.instagram]
  disableInlineCSS = true

  [services.twitter]
  disableInlineCSS = true